### ISSUE TITLE
A more permissive license

### ISSUE THREAD

**Issue by Ejdamm** [sylvainhalle/Bullwinkle#13]
I was thinking about doing improvements to the project but read in the license that I would have to add a notice with my name in each sourcefile I edit. It applies if I redistribute the code and I guess a public fork counts as redistribution. I think it creates redundancy since the changes are saved by git anyway and I would probably rather make the fork private than having to think about changelogs. The easiest solution would be if the license changed.

Could you consider switching to a more permissive license like MIT?

**Comment by codemonstur** [comment]
FYI the file /Source/Parsing/src/ca/uqac/lif/util/package-info.java claims to be copied over from a BeepBeep project and is covered under the GPL. Which might mean that all of Bullwinkle now also needs to be covered under the GPL.

I second the MIT license.

**Comment by sylvainhalle** [comment]
Fine, I'll switch the header comments so that Bullwinkle be released under the MIT license. Due for the next release!
