### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by marinusmaurice** [sylvainhalle/Bullwinkle#15]
Hi, I apologise for logging this here as I couldn't find a comment section.
I just want to say that I'm super impressed with this project and how the thinking is different to all and I'm saying each and every other bnf/language parser/implentation that I have come across.
EXCELLENT STUFF!!!!

Maurice Marinus

**Comment by marinusmaurice** [comment]
May I request with your permission if I may convert this work to another language such as C#, Pascal and Ada?
In fact I came across this work because of work I want to do with regards to Ada. 
If you feel comfortable you may reply here or to my email . marinusmaurice@outlook.com

**Comment by marinusmaurice** [comment]
oh I forgot to add. I will obviously credit you and your work as the original

**Comment by marinusmaurice** [comment]
really really last comment. The full awesomeness of this project has now hit home. Besides the fact it caters for other characters (yes.. i know ALL about that and its refreshing to find another who sees it - brings the count to 2 people I know of, me and you), your solution is ABSOLUTELY DAMN  PHENOMINAL!. Your work should be in textbooks and taught as an example as how to do the simple things right and light and not as other current things which takes a simple thing and makes it weight a tonne.Wow! I cannot compliment you enough!

**Comment by sylvainhalle** [comment]
Wow, thanks for these positive comments. Of course you are free to fork and port Bullwinkle to whatever language you wish. The only thing I would appreciate is to give it a different name and mention that it originates from Bullwinkle.
