### ISSUE TITLE
Maven dependency

### ISSUE THREAD

**Issue by noorbakerally** [sylvainhalle/Bullwinkle#9]
would be good if we could intergrate this tool using maven

**Comment by bramthedev** [comment]
+1

**Comment by sylvainhalle** [comment]
Sorry, I don't work with Maven; none of my 50+ repositories use it and I don't have time to learn it for a single project. If I ever replace Ant with something else, it will be Gradle and not Maven.

**Comment by qyvlik** [comment]
@noorbakerally  @bramthedev

https://jitpack.io/#sylvainhalle/Bullwinkle/v1.4.6

https://stackoverflow.com/questions/8871056/can-i-use-a-github-project-directly-in-maven
